version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  client:
    build: ./client
    ports:
      - 8081:8081
    volumes:
      - ./client:/app
    depends_on:
      - server
  server:
    build: ./server
